// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1DGFZnNQQJzH9ysGHNhO30fTwdjVeOwM',
    appId: '1:500400814556:web:6d899a412d7e0d05f0b719',
    messagingSenderId: '500400814556',
    projectId: 'daily-planning-53307',
    authDomain: 'daily-planning-53307.firebaseapp.com',
    storageBucket: 'daily-planning-53307.firebasestorage.app',
    measurementId: 'G-VZ32EYT79H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwzml6v5GRavTYmF0UJFliAM232RyuDE',
    appId: '1:500400814556:android:7c2fecbdfd151984f0b719',
    messagingSenderId: '500400814556',
    projectId: 'daily-planning-53307',
    storageBucket: 'daily-planning-53307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLVP1NY_9B1nF7KnsTFW2YNk2tFw4EdzU',
    appId: '1:500400814556:ios:0b022d3cb30c1a26f0b719',
    messagingSenderId: '500400814556',
    projectId: 'daily-planning-53307',
    storageBucket: 'daily-planning-53307.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLVP1NY_9B1nF7KnsTFW2YNk2tFw4EdzU',
    appId: '1:500400814556:ios:0b022d3cb30c1a26f0b719',
    messagingSenderId: '500400814556',
    projectId: 'daily-planning-53307',
    storageBucket: 'daily-planning-53307.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1DGFZnNQQJzH9ysGHNhO30fTwdjVeOwM',
    appId: '1:500400814556:web:a051eee450766916f0b719',
    messagingSenderId: '500400814556',
    projectId: 'daily-planning-53307',
    authDomain: 'daily-planning-53307.firebaseapp.com',
    storageBucket: 'daily-planning-53307.firebasestorage.app',
    measurementId: 'G-0FY6PLGHNF',
  );

}